// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "github.com/sterligov/banner-rotator/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Bandit is an autogenerated mock type for the Bandit type
type Bandit struct {
	mock.Mock
}

// SelectBanner provides a mock function with given fields: stats
func (_m *Bandit) SelectBanner(stats []model.Statistic) int64 {
	ret := _m.Called(stats)

	var r0 int64
	if rf, ok := ret.Get(0).(func([]model.Statistic) int64); ok {
		r0 = rf(stats)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}
