// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sterligov/banner-rotator/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// BannerUseCase is an autogenerated mock type for the BannerUseCase type
type BannerUseCase struct {
	mock.Mock
}

// CreateBanner provides a mock function with given fields: ctx, b
func (_m *BannerUseCase) CreateBanner(ctx context.Context, b model.Banner) (int64, error) {
	ret := _m.Called(ctx, b)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, model.Banner) int64); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Banner) error); ok {
		r1 = rf(ctx, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateBannerSlotRelation provides a mock function with given fields: ctx, bannerID, slotID
func (_m *BannerUseCase) CreateBannerSlotRelation(ctx context.Context, bannerID int64, slotID int64) (int64, error) {
	ret := _m.Called(ctx, bannerID, slotID)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) int64); ok {
		r0 = rf(ctx, bannerID, slotID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, bannerID, slotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBannerByID provides a mock function with given fields: ctx, id
func (_m *BannerUseCase) DeleteBannerByID(ctx context.Context, id int64) (int64, error) {
	ret := _m.Called(ctx, id)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBannerSlotRelation provides a mock function with given fields: ctx, bannerID, slotID
func (_m *BannerUseCase) DeleteBannerSlotRelation(ctx context.Context, bannerID int64, slotID int64) (int64, error) {
	ret := _m.Called(ctx, bannerID, slotID)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) int64); ok {
		r0 = rf(ctx, bannerID, slotID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, bannerID, slotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllBanners provides a mock function with given fields: ctx
func (_m *BannerUseCase) FindAllBanners(ctx context.Context) ([]model.Banner, error) {
	ret := _m.Called(ctx)

	var r0 []model.Banner
	if rf, ok := ret.Get(0).(func(context.Context) []model.Banner); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Banner)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBannerByID provides a mock function with given fields: ctx, id
func (_m *BannerUseCase) FindBannerByID(ctx context.Context, id int64) (model.Banner, error) {
	ret := _m.Called(ctx, id)

	var r0 model.Banner
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Banner); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Banner)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterClick provides a mock function with given fields: ctx, bannerID, slotID, groupID
func (_m *BannerUseCase) RegisterClick(ctx context.Context, bannerID int64, slotID int64, groupID int64) error {
	ret := _m.Called(ctx, bannerID, slotID, groupID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) error); ok {
		r0 = rf(ctx, bannerID, slotID, groupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectBanner provides a mock function with given fields: ctx, slotID, groupID
func (_m *BannerUseCase) SelectBanner(ctx context.Context, slotID int64, groupID int64) (int64, error) {
	ret := _m.Called(ctx, slotID, groupID)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) int64); ok {
		r0 = rf(ctx, slotID, groupID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, slotID, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBanner provides a mock function with given fields: ctx, b
func (_m *BannerUseCase) UpdateBanner(ctx context.Context, b model.Banner) (int64, error) {
	ret := _m.Called(ctx, b)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, model.Banner) int64); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Banner) error); ok {
		r1 = rf(ctx, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
