// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sterligov/banner-rotator/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// SlotUseCase is an autogenerated mock type for the SlotUseCase type
type SlotUseCase struct {
	mock.Mock
}

// CreateSlot provides a mock function with given fields: ctx, b
func (_m *SlotUseCase) CreateSlot(ctx context.Context, b model.Slot) (int64, error) {
	ret := _m.Called(ctx, b)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, model.Slot) int64); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Slot) error); ok {
		r1 = rf(ctx, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSlotByID provides a mock function with given fields: ctx, id
func (_m *SlotUseCase) DeleteSlotByID(ctx context.Context, id int64) (int64, error) {
	ret := _m.Called(ctx, id)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllSlots provides a mock function with given fields: ctx
func (_m *SlotUseCase) FindAllSlots(ctx context.Context) ([]model.Slot, error) {
	ret := _m.Called(ctx)

	var r0 []model.Slot
	if rf, ok := ret.Get(0).(func(context.Context) []model.Slot); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Slot)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSlotByID provides a mock function with given fields: ctx, id
func (_m *SlotUseCase) FindSlotByID(ctx context.Context, id int64) (model.Slot, error) {
	ret := _m.Called(ctx, id)

	var r0 model.Slot
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Slot); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Slot)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSlot provides a mock function with given fields: ctx, b
func (_m *SlotUseCase) UpdateSlot(ctx context.Context, b model.Slot) (int64, error) {
	ret := _m.Called(ctx, b)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, model.Slot) int64); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Slot) error); ok {
		r1 = rf(ctx, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
