// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: api/banner_service.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Banner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Banner) Reset() {
	*x = Banner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{0}
}

func (x *Banner) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Banner) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type FindBannerByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindBannerByIDRequest) Reset() {
	*x = FindBannerByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBannerByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBannerByIDRequest) ProtoMessage() {}

func (x *FindBannerByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBannerByIDRequest.ProtoReflect.Descriptor instead.
func (*FindBannerByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{1}
}

func (x *FindBannerByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindBannerByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Banner *Banner `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
}

func (x *FindBannerByIDResponse) Reset() {
	*x = FindBannerByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBannerByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBannerByIDResponse) ProtoMessage() {}

func (x *FindBannerByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBannerByIDResponse.ProtoReflect.Descriptor instead.
func (*FindBannerByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{2}
}

func (x *FindBannerByIDResponse) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

type FindAllBannersBySlotIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotId int64 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
}

func (x *FindAllBannersBySlotIDRequest) Reset() {
	*x = FindAllBannersBySlotIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllBannersBySlotIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllBannersBySlotIDRequest) ProtoMessage() {}

func (x *FindAllBannersBySlotIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllBannersBySlotIDRequest.ProtoReflect.Descriptor instead.
func (*FindAllBannersBySlotIDRequest) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{3}
}

func (x *FindAllBannersBySlotIDRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type FindAllBannersBySlotIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Banners []*Banner `protobuf:"bytes,1,rep,name=banners,proto3" json:"banners,omitempty"`
}

func (x *FindAllBannersBySlotIDResponse) Reset() {
	*x = FindAllBannersBySlotIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllBannersBySlotIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllBannersBySlotIDResponse) ProtoMessage() {}

func (x *FindAllBannersBySlotIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllBannersBySlotIDResponse.ProtoReflect.Descriptor instead.
func (*FindAllBannersBySlotIDResponse) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{4}
}

func (x *FindAllBannersBySlotIDResponse) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

type CreateBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Banner *Banner `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
}

func (x *CreateBannerRequest) Reset() {
	*x = CreateBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBannerRequest) ProtoMessage() {}

func (x *CreateBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBannerRequest.ProtoReflect.Descriptor instead.
func (*CreateBannerRequest) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBannerRequest) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

type FindAllBannersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllBannersRequest) Reset() {
	*x = FindAllBannersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllBannersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllBannersRequest) ProtoMessage() {}

func (x *FindAllBannersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllBannersRequest.ProtoReflect.Descriptor instead.
func (*FindAllBannersRequest) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{6}
}

type FindAllBannersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Banners []*Banner `protobuf:"bytes,1,rep,name=banners,proto3" json:"banners,omitempty"`
}

func (x *FindAllBannersResponse) Reset() {
	*x = FindAllBannersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllBannersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllBannersResponse) ProtoMessage() {}

func (x *FindAllBannersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllBannersResponse.ProtoReflect.Descriptor instead.
func (*FindAllBannersResponse) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllBannersResponse) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

type CreateBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InsertedId int64 `protobuf:"varint,1,opt,name=inserted_id,json=insertedId,proto3" json:"inserted_id,omitempty"`
}

func (x *CreateBannerResponse) Reset() {
	*x = CreateBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBannerResponse) ProtoMessage() {}

func (x *CreateBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBannerResponse.ProtoReflect.Descriptor instead.
func (*CreateBannerResponse) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateBannerResponse) GetInsertedId() int64 {
	if x != nil {
		return x.InsertedId
	}
	return 0
}

type DeleteBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBannerRequest) Reset() {
	*x = DeleteBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBannerRequest) ProtoMessage() {}

func (x *DeleteBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBannerRequest.ProtoReflect.Descriptor instead.
func (*DeleteBannerRequest) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBannerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Affected int64 `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
}

func (x *DeleteBannerResponse) Reset() {
	*x = DeleteBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBannerResponse) ProtoMessage() {}

func (x *DeleteBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBannerResponse.ProtoReflect.Descriptor instead.
func (*DeleteBannerResponse) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBannerResponse) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

type UpdateBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Banner *Banner `protobuf:"bytes,2,opt,name=banner,proto3" json:"banner,omitempty"`
}

func (x *UpdateBannerRequest) Reset() {
	*x = UpdateBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBannerRequest) ProtoMessage() {}

func (x *UpdateBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBannerRequest.ProtoReflect.Descriptor instead.
func (*UpdateBannerRequest) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateBannerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBannerRequest) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

type UpdateBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Affected int64 `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
}

func (x *UpdateBannerResponse) Reset() {
	*x = UpdateBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBannerResponse) ProtoMessage() {}

func (x *UpdateBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBannerResponse.ProtoReflect.Descriptor instead.
func (*UpdateBannerResponse) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateBannerResponse) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

type CreateBannerSlotRelationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InsertedId int64 `protobuf:"varint,1,opt,name=inserted_id,json=insertedId,proto3" json:"inserted_id,omitempty"`
}

func (x *CreateBannerSlotRelationResponse) Reset() {
	*x = CreateBannerSlotRelationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBannerSlotRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBannerSlotRelationResponse) ProtoMessage() {}

func (x *CreateBannerSlotRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBannerSlotRelationResponse.ProtoReflect.Descriptor instead.
func (*CreateBannerSlotRelationResponse) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateBannerSlotRelationResponse) GetInsertedId() int64 {
	if x != nil {
		return x.InsertedId
	}
	return 0
}

type CreateBannerSlotRelationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerId int64 `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	SlotId   int64 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
}

func (x *CreateBannerSlotRelationRequest) Reset() {
	*x = CreateBannerSlotRelationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBannerSlotRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBannerSlotRelationRequest) ProtoMessage() {}

func (x *CreateBannerSlotRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBannerSlotRelationRequest.ProtoReflect.Descriptor instead.
func (*CreateBannerSlotRelationRequest) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{14}
}

func (x *CreateBannerSlotRelationRequest) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *CreateBannerSlotRelationRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type DeleteBannerSlotRelationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerId int64 `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	SlotId   int64 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
}

func (x *DeleteBannerSlotRelationRequest) Reset() {
	*x = DeleteBannerSlotRelationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBannerSlotRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBannerSlotRelationRequest) ProtoMessage() {}

func (x *DeleteBannerSlotRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBannerSlotRelationRequest.ProtoReflect.Descriptor instead.
func (*DeleteBannerSlotRelationRequest) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteBannerSlotRelationRequest) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *DeleteBannerSlotRelationRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type DeleteBannerSlotRelationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Affected int64 `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
}

func (x *DeleteBannerSlotRelationResponse) Reset() {
	*x = DeleteBannerSlotRelationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBannerSlotRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBannerSlotRelationResponse) ProtoMessage() {}

func (x *DeleteBannerSlotRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBannerSlotRelationResponse.ProtoReflect.Descriptor instead.
func (*DeleteBannerSlotRelationResponse) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteBannerSlotRelationResponse) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

type RegisterClickRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerId int64 `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	SlotId   int64 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	GroupId  int64 `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *RegisterClickRequest) Reset() {
	*x = RegisterClickRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClickRequest) ProtoMessage() {}

func (x *RegisterClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClickRequest.ProtoReflect.Descriptor instead.
func (*RegisterClickRequest) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterClickRequest) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *RegisterClickRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *RegisterClickRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type SelectBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotId  int64 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	GroupId int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *SelectBannerRequest) Reset() {
	*x = SelectBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectBannerRequest) ProtoMessage() {}

func (x *SelectBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectBannerRequest.ProtoReflect.Descriptor instead.
func (*SelectBannerRequest) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{18}
}

func (x *SelectBannerRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SelectBannerRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type SelectBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerId int64 `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
}

func (x *SelectBannerResponse) Reset() {
	*x = SelectBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectBannerResponse) ProtoMessage() {}

func (x *SelectBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectBannerResponse.ProtoReflect.Descriptor instead.
func (*SelectBannerResponse) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{19}
}

func (x *SelectBannerResponse) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

type RegisterClickResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterClickResponse) Reset() {
	*x = RegisterClickResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_banner_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterClickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClickResponse) ProtoMessage() {}

func (x *RegisterClickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_banner_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClickResponse.ProtoReflect.Descriptor instead.
func (*RegisterClickResponse) Descriptor() ([]byte, []int) {
	return file_api_banner_service_proto_rawDescGZIP(), []int{20}
}

var File_api_banner_service_proto protoreflect.FileDescriptor

var file_api_banner_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3a, 0x0a, 0x06, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x15,
	0x46, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x26, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52,
	0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x38, 0x0a, 0x1d, 0x46, 0x69, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x42, 0x79, 0x53, 0x6c, 0x6f, 0x74, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49,
	0x64, 0x22, 0x4a, 0x0a, 0x1e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x73, 0x42, 0x79, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x52, 0x07, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x3d, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x52, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x17, 0x0a, 0x15,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x28, 0x0a, 0x07, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x52, 0x07, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x37, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64,
	0x49, 0x64, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x14, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x4d, 0x0a,
	0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x52, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x22, 0x43, 0x0a, 0x20, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x65, 0x64, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x57,
	0x0a, 0x1f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x6c,
	0x6f, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x20, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61,
	0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61,
	0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x67, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x22, 0x49, 0x0a, 0x13, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x14, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xde, 0x09, 0x0a, 0x0d, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a, 0x0e, 0x46,
	0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1d, 0x2e,
	0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x61, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x1d, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x10, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x12, 0x08, 0x2f, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x89, 0x01, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x42, 0x79, 0x53, 0x6c, 0x6f, 0x74, 0x49,
	0x44, 0x12, 0x25, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x42, 0x79, 0x53, 0x6c, 0x6f, 0x74, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73,
	0x42, 0x79, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x12, 0x18, 0x2f, 0x73, 0x6c, 0x6f, 0x74, 0x73,
	0x2f, 0x7b, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x73, 0x12, 0x5b, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x12, 0x1b, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x10, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x22, 0x08, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x12,
	0x60, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12,
	0x1b, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0f, 0x2a, 0x0d, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2f, 0x7b, 0x69, 0x64,
	0x7d, 0x12, 0x60, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x12, 0x1b, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0f, 0x1a, 0x0d, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x9b, 0x01, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x27, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x62, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53,
	0x6c, 0x6f, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26, 0x22, 0x24, 0x2f, 0x62, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2f, 0x7b, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x7d, 0x2f, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x2f, 0x7b, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64,
	0x7d, 0x12, 0x9b, 0x01, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27,
	0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x6c, 0x6f,
	0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26, 0x2a, 0x24, 0x2f, 0x62, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x73, 0x2f, 0x7b, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x7d, 0x2f,
	0x73, 0x6c, 0x6f, 0x74, 0x73, 0x2f, 0x7b, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x7d, 0x12,
	0x92, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x63,
	0x6b, 0x12, 0x1c, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x44,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x3e, 0x22, 0x3c, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73,
	0x2f, 0x7b, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x73, 0x6c, 0x6f,
	0x74, 0x73, 0x2f, 0x7b, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x2f, 0x7b, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x63,
	0x6c, 0x69, 0x63, 0x6b, 0x12, 0x83, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x42,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x38, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x32, 0x12, 0x30, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x73, 0x2f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f,
	0x7b, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x73, 0x6c, 0x6f, 0x74, 0x73,
	0x2f, 0x7b, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x7d, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_banner_service_proto_rawDescOnce sync.Once
	file_api_banner_service_proto_rawDescData = file_api_banner_service_proto_rawDesc
)

func file_api_banner_service_proto_rawDescGZIP() []byte {
	file_api_banner_service_proto_rawDescOnce.Do(func() {
		file_api_banner_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_banner_service_proto_rawDescData)
	})
	return file_api_banner_service_proto_rawDescData
}

var file_api_banner_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_banner_service_proto_goTypes = []interface{}{
	(*Banner)(nil),                           // 0: banner.Banner
	(*FindBannerByIDRequest)(nil),            // 1: banner.FindBannerByIDRequest
	(*FindBannerByIDResponse)(nil),           // 2: banner.FindBannerByIDResponse
	(*FindAllBannersBySlotIDRequest)(nil),    // 3: banner.FindAllBannersBySlotIDRequest
	(*FindAllBannersBySlotIDResponse)(nil),   // 4: banner.FindAllBannersBySlotIDResponse
	(*CreateBannerRequest)(nil),              // 5: banner.CreateBannerRequest
	(*FindAllBannersRequest)(nil),            // 6: banner.FindAllBannersRequest
	(*FindAllBannersResponse)(nil),           // 7: banner.FindAllBannersResponse
	(*CreateBannerResponse)(nil),             // 8: banner.CreateBannerResponse
	(*DeleteBannerRequest)(nil),              // 9: banner.DeleteBannerRequest
	(*DeleteBannerResponse)(nil),             // 10: banner.DeleteBannerResponse
	(*UpdateBannerRequest)(nil),              // 11: banner.UpdateBannerRequest
	(*UpdateBannerResponse)(nil),             // 12: banner.UpdateBannerResponse
	(*CreateBannerSlotRelationResponse)(nil), // 13: banner.CreateBannerSlotRelationResponse
	(*CreateBannerSlotRelationRequest)(nil),  // 14: banner.CreateBannerSlotRelationRequest
	(*DeleteBannerSlotRelationRequest)(nil),  // 15: banner.DeleteBannerSlotRelationRequest
	(*DeleteBannerSlotRelationResponse)(nil), // 16: banner.DeleteBannerSlotRelationResponse
	(*RegisterClickRequest)(nil),             // 17: banner.RegisterClickRequest
	(*SelectBannerRequest)(nil),              // 18: banner.SelectBannerRequest
	(*SelectBannerResponse)(nil),             // 19: banner.SelectBannerResponse
	(*RegisterClickResponse)(nil),            // 20: banner.RegisterClickResponse
}
var file_api_banner_service_proto_depIdxs = []int32{
	0,  // 0: banner.FindBannerByIDResponse.banner:type_name -> banner.Banner
	0,  // 1: banner.FindAllBannersBySlotIDResponse.banners:type_name -> banner.Banner
	0,  // 2: banner.CreateBannerRequest.banner:type_name -> banner.Banner
	0,  // 3: banner.FindAllBannersResponse.banners:type_name -> banner.Banner
	0,  // 4: banner.UpdateBannerRequest.banner:type_name -> banner.Banner
	1,  // 5: banner.BannerService.FindBannerByID:input_type -> banner.FindBannerByIDRequest
	6,  // 6: banner.BannerService.FindAllBanners:input_type -> banner.FindAllBannersRequest
	3,  // 7: banner.BannerService.FindAllBannersBySlotID:input_type -> banner.FindAllBannersBySlotIDRequest
	5,  // 8: banner.BannerService.CreateBanner:input_type -> banner.CreateBannerRequest
	9,  // 9: banner.BannerService.DeleteBanner:input_type -> banner.DeleteBannerRequest
	11, // 10: banner.BannerService.UpdateBanner:input_type -> banner.UpdateBannerRequest
	14, // 11: banner.BannerService.CreateBannerSlotRelation:input_type -> banner.CreateBannerSlotRelationRequest
	15, // 12: banner.BannerService.DeleteBannerSlotRelation:input_type -> banner.DeleteBannerSlotRelationRequest
	17, // 13: banner.BannerService.RegisterClick:input_type -> banner.RegisterClickRequest
	18, // 14: banner.BannerService.SelectBanner:input_type -> banner.SelectBannerRequest
	2,  // 15: banner.BannerService.FindBannerByID:output_type -> banner.FindBannerByIDResponse
	7,  // 16: banner.BannerService.FindAllBanners:output_type -> banner.FindAllBannersResponse
	4,  // 17: banner.BannerService.FindAllBannersBySlotID:output_type -> banner.FindAllBannersBySlotIDResponse
	8,  // 18: banner.BannerService.CreateBanner:output_type -> banner.CreateBannerResponse
	10, // 19: banner.BannerService.DeleteBanner:output_type -> banner.DeleteBannerResponse
	12, // 20: banner.BannerService.UpdateBanner:output_type -> banner.UpdateBannerResponse
	13, // 21: banner.BannerService.CreateBannerSlotRelation:output_type -> banner.CreateBannerSlotRelationResponse
	16, // 22: banner.BannerService.DeleteBannerSlotRelation:output_type -> banner.DeleteBannerSlotRelationResponse
	20, // 23: banner.BannerService.RegisterClick:output_type -> banner.RegisterClickResponse
	19, // 24: banner.BannerService.SelectBanner:output_type -> banner.SelectBannerResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_banner_service_proto_init() }
func file_api_banner_service_proto_init() {
	if File_api_banner_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_banner_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBannerByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBannerByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllBannersBySlotIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllBannersBySlotIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllBannersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllBannersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBannerSlotRelationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBannerSlotRelationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBannerSlotRelationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBannerSlotRelationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterClickRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_banner_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterClickResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_banner_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_banner_service_proto_goTypes,
		DependencyIndexes: file_api_banner_service_proto_depIdxs,
		MessageInfos:      file_api_banner_service_proto_msgTypes,
	}.Build()
	File_api_banner_service_proto = out.File
	file_api_banner_service_proto_rawDesc = nil
	file_api_banner_service_proto_goTypes = nil
	file_api_banner_service_proto_depIdxs = nil
}
