// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: api/slot_service.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Slot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Slot) Reset() {
	*x = Slot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_slot_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_api_slot_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_api_slot_service_proto_rawDescGZIP(), []int{0}
}

func (x *Slot) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Slot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type FindSlotByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot *Slot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *FindSlotByIDResponse) Reset() {
	*x = FindSlotByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_slot_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSlotByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSlotByIDResponse) ProtoMessage() {}

func (x *FindSlotByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_slot_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSlotByIDResponse.ProtoReflect.Descriptor instead.
func (*FindSlotByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_slot_service_proto_rawDescGZIP(), []int{1}
}

func (x *FindSlotByIDResponse) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

type FindSlotByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindSlotByIDRequest) Reset() {
	*x = FindSlotByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_slot_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSlotByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSlotByIDRequest) ProtoMessage() {}

func (x *FindSlotByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_slot_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSlotByIDRequest.ProtoReflect.Descriptor instead.
func (*FindSlotByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_slot_service_proto_rawDescGZIP(), []int{2}
}

func (x *FindSlotByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindAllSlotsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllSlotsRequest) Reset() {
	*x = FindAllSlotsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_slot_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllSlotsRequest) ProtoMessage() {}

func (x *FindAllSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_slot_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllSlotsRequest.ProtoReflect.Descriptor instead.
func (*FindAllSlotsRequest) Descriptor() ([]byte, []int) {
	return file_api_slot_service_proto_rawDescGZIP(), []int{3}
}

type FindAllSlotsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slots []*Slot `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
}

func (x *FindAllSlotsResponse) Reset() {
	*x = FindAllSlotsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_slot_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllSlotsResponse) ProtoMessage() {}

func (x *FindAllSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_slot_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllSlotsResponse.ProtoReflect.Descriptor instead.
func (*FindAllSlotsResponse) Descriptor() ([]byte, []int) {
	return file_api_slot_service_proto_rawDescGZIP(), []int{4}
}

func (x *FindAllSlotsResponse) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type CreateSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot *Slot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *CreateSlotRequest) Reset() {
	*x = CreateSlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_slot_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSlotRequest) ProtoMessage() {}

func (x *CreateSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_slot_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSlotRequest.ProtoReflect.Descriptor instead.
func (*CreateSlotRequest) Descriptor() ([]byte, []int) {
	return file_api_slot_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSlotRequest) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

type CreateSlotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InsertedId int64 `protobuf:"varint,1,opt,name=inserted_id,json=insertedId,proto3" json:"inserted_id,omitempty"`
}

func (x *CreateSlotResponse) Reset() {
	*x = CreateSlotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_slot_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSlotResponse) ProtoMessage() {}

func (x *CreateSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_slot_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSlotResponse.ProtoReflect.Descriptor instead.
func (*CreateSlotResponse) Descriptor() ([]byte, []int) {
	return file_api_slot_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSlotResponse) GetInsertedId() int64 {
	if x != nil {
		return x.InsertedId
	}
	return 0
}

type DeleteSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSlotRequest) Reset() {
	*x = DeleteSlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_slot_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSlotRequest) ProtoMessage() {}

func (x *DeleteSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_slot_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSlotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSlotRequest) Descriptor() ([]byte, []int) {
	return file_api_slot_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSlotRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSlotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Affected int64 `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
}

func (x *DeleteSlotResponse) Reset() {
	*x = DeleteSlotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_slot_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSlotResponse) ProtoMessage() {}

func (x *DeleteSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_slot_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSlotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSlotResponse) Descriptor() ([]byte, []int) {
	return file_api_slot_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSlotResponse) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

type UpdateSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slot *Slot `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *UpdateSlotRequest) Reset() {
	*x = UpdateSlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_slot_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSlotRequest) ProtoMessage() {}

func (x *UpdateSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_slot_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSlotRequest.ProtoReflect.Descriptor instead.
func (*UpdateSlotRequest) Descriptor() ([]byte, []int) {
	return file_api_slot_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSlotRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSlotRequest) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

type UpdateSlotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Affected int64 `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
}

func (x *UpdateSlotResponse) Reset() {
	*x = UpdateSlotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_slot_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSlotResponse) ProtoMessage() {}

func (x *UpdateSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_slot_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSlotResponse.ProtoReflect.Descriptor instead.
func (*UpdateSlotResponse) Descriptor() ([]byte, []int) {
	return file_api_slot_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSlotResponse) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

var File_api_slot_service_proto protoreflect.FileDescriptor

var file_api_slot_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x04,
	0x53, 0x6c, 0x6f, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x14, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x6c,
	0x6f, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73,
	0x6c, 0x6f, 0x74, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x25,
	0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x14,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52,
	0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x22, 0x33, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x73,
	0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x6c, 0x6f, 0x74,
	0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x35, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64,
	0x49, 0x64, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6c, 0x6f, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x43, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e,
	0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73,
	0x6c, 0x6f, 0x74, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x30,
	0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x32, 0xbe, 0x03, 0x0a, 0x0b, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x5a, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x79, 0x49, 0x44,
	0x12, 0x19, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x6c, 0x6f, 0x74,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x6c,
	0x6f, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x12,
	0x0b, 0x2f, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x55, 0x0a, 0x0c,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x73,
	0x6c, 0x6f, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x53, 0x6c, 0x6f, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x0e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x08, 0x12, 0x06, 0x2f, 0x73, 0x6c,
	0x6f, 0x74, 0x73, 0x12, 0x4f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6c, 0x6f,
	0x74, 0x12, 0x17, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x6c, 0x6f,
	0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x08, 0x22, 0x06, 0x2f, 0x73,
	0x6c, 0x6f, 0x74, 0x73, 0x12, 0x54, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6c,
	0x6f, 0x74, 0x12, 0x17, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x6c,
	0x6f, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x2a, 0x0b, 0x2f,
	0x73, 0x6c, 0x6f, 0x74, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x55, 0x0a, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x17, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0e, 0x1a, 0x0c, 0x2f, 0x2d, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x2f, 0x7b, 0x69, 0x64,
	0x7d, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_slot_service_proto_rawDescOnce sync.Once
	file_api_slot_service_proto_rawDescData = file_api_slot_service_proto_rawDesc
)

func file_api_slot_service_proto_rawDescGZIP() []byte {
	file_api_slot_service_proto_rawDescOnce.Do(func() {
		file_api_slot_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_slot_service_proto_rawDescData)
	})
	return file_api_slot_service_proto_rawDescData
}

var file_api_slot_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_slot_service_proto_goTypes = []interface{}{
	(*Slot)(nil),                 // 0: slot.Slot
	(*FindSlotByIDResponse)(nil), // 1: slot.FindSlotByIDResponse
	(*FindSlotByIDRequest)(nil),  // 2: slot.FindSlotByIDRequest
	(*FindAllSlotsRequest)(nil),  // 3: slot.FindAllSlotsRequest
	(*FindAllSlotsResponse)(nil), // 4: slot.FindAllSlotsResponse
	(*CreateSlotRequest)(nil),    // 5: slot.CreateSlotRequest
	(*CreateSlotResponse)(nil),   // 6: slot.CreateSlotResponse
	(*DeleteSlotRequest)(nil),    // 7: slot.DeleteSlotRequest
	(*DeleteSlotResponse)(nil),   // 8: slot.DeleteSlotResponse
	(*UpdateSlotRequest)(nil),    // 9: slot.UpdateSlotRequest
	(*UpdateSlotResponse)(nil),   // 10: slot.UpdateSlotResponse
}
var file_api_slot_service_proto_depIdxs = []int32{
	0,  // 0: slot.FindSlotByIDResponse.slot:type_name -> slot.Slot
	0,  // 1: slot.FindAllSlotsResponse.slots:type_name -> slot.Slot
	0,  // 2: slot.CreateSlotRequest.slot:type_name -> slot.Slot
	0,  // 3: slot.UpdateSlotRequest.slot:type_name -> slot.Slot
	2,  // 4: slot.SlotService.FindSlotByID:input_type -> slot.FindSlotByIDRequest
	3,  // 5: slot.SlotService.FindAllSlots:input_type -> slot.FindAllSlotsRequest
	5,  // 6: slot.SlotService.CreateSlot:input_type -> slot.CreateSlotRequest
	7,  // 7: slot.SlotService.DeleteSlot:input_type -> slot.DeleteSlotRequest
	9,  // 8: slot.SlotService.UpdateSlot:input_type -> slot.UpdateSlotRequest
	1,  // 9: slot.SlotService.FindSlotByID:output_type -> slot.FindSlotByIDResponse
	4,  // 10: slot.SlotService.FindAllSlots:output_type -> slot.FindAllSlotsResponse
	6,  // 11: slot.SlotService.CreateSlot:output_type -> slot.CreateSlotResponse
	8,  // 12: slot.SlotService.DeleteSlot:output_type -> slot.DeleteSlotResponse
	10, // 13: slot.SlotService.UpdateSlot:output_type -> slot.UpdateSlotResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_slot_service_proto_init() }
func file_api_slot_service_proto_init() {
	if File_api_slot_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_slot_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_slot_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSlotByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_slot_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSlotByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_slot_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllSlotsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_slot_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllSlotsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_slot_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_slot_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSlotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_slot_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_slot_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSlotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_slot_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_slot_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSlotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_slot_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_slot_service_proto_goTypes,
		DependencyIndexes: file_api_slot_service_proto_depIdxs,
		MessageInfos:      file_api_slot_service_proto_msgTypes,
	}.Build()
	File_api_slot_service_proto = out.File
	file_api_slot_service_proto_rawDesc = nil
	file_api_slot_service_proto_goTypes = nil
	file_api_slot_service_proto_depIdxs = nil
}
