version: '3.5'

services:
  rotator_integration:
    build:
      context: ../
      dockerfile: ./build/integration-tests.Dockerfile
    networks:
      - rotator_test_net

networks:
  rotator_test_net:
    external:
      name: rotator_net
