version: "3"

services:
  rotator-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

#  rotator-api:
#    build:
#      context: ../
#      dockerfile: ./build/Dockerfile
#    ports:
#      - 8082:8082

  rotator-nats:
    image: nats:2.1.9-alpine3.12
    ports:
      - 8222:8222
      - 4222:4222
