version: '3.5'

services:
  rotator_db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${DB_PORT}:3306

  rotator_nats:
    image: nats:2.1.9-alpine3.12
    ports:
      - ${NATS_HTTP_PORT}:8222
      - ${NATS_PORT}:4222

  rotator_api:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    ports:
      - ${APP_HTTP_PORT}:8081
      - ${APP_GRPC_PORT}:8082
    depends_on:
      - rotator_db
      - rotator_nats

  rotator_migrations:
    build:
      context: ../
      dockerfile: ./build/migrations.Dockerfile
    command: ["rotator_db:3306", "-t", "60", "--", "/go/bin/goose", "mysql", "${DB_USER}:${DB_PASSWORD}@tcp(rotator_db:3306)/${DB_NAME}?parseTime=true", "up"]
    depends_on:
      - rotator_db

networks:
  default:
    name: rotator_net
