os: linux

language: go

go:
  - 1.15.x

env: GO111MODULE=on

stages:
  - name: Tests

jobs:
  include:
    - stage: "Tests"
      name: "Linters"
      install: go install github.com/golangci/golangci-lint/cmd/golangci-lint
      script: golangci-lint run ./...

    - stage: "Tests"
      name: "Unit tests"
      install: go mod download
      script: go test -v -count=100 -race ./...

    - stage: "Tests"
      name: "Build"
      install: go mod download
      script: cd cmd && go build
