language: go

go:
  - "1.15"

os:
  - linux

env: GO111MODULE=on

stages:
  - name: Tests

jobs:
  include:
    - stage: "Tests"
      name: "Linters"
      install: go install github.com/golangci/golangci-lint/cmd/golangci-lint
      script: golangci-lint run ./...

    - stage: "Tests"
      name: "Unit tests"
      install: go mod download
      script: go test -race -count=100 ./...

    - stage: "Tests"
      name: "Integration tests"
      install: go mod download
      script: make integration-test

    - stage: "Tests"
      name: "Build"
      install: go mod download
      script: go build -o rotator ./cmd
