logger:
  level: info
  path: stderr

http:
  addr: :8081
  write_timeout: 5s
  read_timeout: 5s
  handler_timeout: 5s

grpc:
  addr: :8082

database:
  connection_addr: rotator_user:rotator_pass@tcp(rotator_db:3306)/rotator?parseTime=true
  driver: mysql
  reconnect_time: 3s
  max_reconnect_retries: 20
  max_open_conns: 20
  max_idle_conns: 20
  max_conn_lifetime: 5m

nats:
  url: nats://rotator_nats:4222
  connect_timeout: 10s
  connect_time_wait: 1s
  reconnect_time: 2s
  max_reconnect_retries: 10

queue:
  subject: rotator
